# Generated by Django 4.2.18 on 2025-03-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('decription', models.TextField()),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('button_link', models.URLField(default='#')),
                ('image', models.ImageField(upload_to='slider_images/')),
            ],
        ),
    ]
