# Generated by Django 4.2.18 on 2025-03-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
