# Generated by Django 4.2.18 on 2025-03-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_slider_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='decription',
            new_name='description',
        ),
    ]
