# Generated by Django 4.2.18 on 2025-03-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_decription_slider_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(choices=[('flaticon-server', 'Server'), ('flaticon-cloud', 'Cloud'), ('flaticon-database', 'Database'), ('flaticon-network', 'Network'), ('flaticon-security', 'Security'), ('flaticon-settings', 'Settings')], default='flaticon-server', max_length=100)),
                ('image', models.ImageField(upload_to='service/')),
                ('order', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
