# Generated by Django 4.2.18 on 2025-03-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(default='service.html'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(choices=[('flaticon-green', 'Green Icon'), ('flaticon-rocket', 'Rocket Icon'), ('flaticon-settings', 'Settings Icon'), ('flaticon-global', 'Global Icon'), ('flaticon-shield', 'Shield Icon')], default='flaticon-green', help_text='Select an icon for the service.', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services/shape-services.png', upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which services appear'),
        ),
    ]
