# Generated by Django 4.2.18 on 2025-03-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_service_options_service_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.AddField(
            model_name='service',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(choices=[('flaticon-green', 'Green Icon'), ('flaticon-rocket', 'Rocket Icon'), ('flaticon-settings', 'Settings Icon'), ('flaticon-global', 'Global Icon'), ('flaticon-shield', 'Shield Icon'), ('flaticon-server', 'Server Icon'), ('flaticon-cloud', 'Cloud Icon'), ('flaticon-security', 'Security Icon'), ('flaticon-database', 'Database Icon')], default='flaticon-green', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.URLField(default='http://localhost'),
        ),
    ]
