# Generated by Django 4.2.18 on 2025-03-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_service_options_remove_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_heading',
            field=models.TextField(default='Default Heading'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_subheading',
            field=models.TextField(default='Default subHeading'),
        ),
    ]
