# Generated by Django 4.2.18 on 2025-03-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_service_heading_service_service_subheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_heading',
            field=models.CharField(default='Default Heading', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_subheading',
            field=models.CharField(default='Default subHeading', max_length=50),
        ),
    ]
