# Generated by Django 4.2.18 on 2025-03-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_service_service_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dummy Text', max_length=255)),
                ('subtitle', models.CharField(default='Dummy Text', max_length=255)),
            ],
        ),
    ]
