# Generated by Django 4.2.18 on 2025-03-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dummy Text', max_length=255)),
                ('subtitle', models.CharField(default='DUmmy Text', max_length=255)),
                ('description_1', models.TextField(default='Default Descripton 1')),
                ('description_2', models.TextField(default='Default Description 2')),
                ('button_text', models.CharField(default='Get started', max_length=50)),
                ('button_link', models.URLField(default='#', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='about_images/')),
            ],
        ),
    ]
