# Generated by Django 4.2.18 on 2025-03-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pricingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='dummy text', max_length=255)),
                ('subtitle', models.CharField(default='dummy text', max_length=255)),
                ('description', models.TextField(default='our expert')),
                ('phone_number', models.CharField(default='xx-xxxxxx', max_length=20)),
                ('text_field', models.TextField(default='text_us', max_length=50)),
            ],
        ),
    ]
