# Generated by Django 4.2.18 on 2025-03-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_phonedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedetail',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phonedetail',
            name='cnic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
