# Generated by Django 4.2.18 on 2025-03-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_phonedetail_address_alter_phonedetail_cnic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='default_logo.png', upload_to='footer_logos/')),
                ('phone', models.CharField(default='+1 514 648 256', max_length=20)),
                ('email', models.EmailField(default='youremail@gmail.com', max_length=254)),
                ('address', models.TextField(default='123 East 26th Street, Fifth Floor, New York, NY 10011')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
